// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proiect_Medii_Programare.Data;

#nullable disable

namespace Proiect_Medii_Programare.Migrations
{
    [DbContext(typeof(Proiect_Medii_ProgramareContext))]
    [Migration("20231229205726_Recenzie")]
    partial class Recenzie
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Proiect_Medii_Programare.Models.Recenzie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Comentariu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Recenzie");
                });

            modelBuilder.Entity("Proiect_Medii_Programare.Models.Restaurant", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NrTelefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RatingTotal")
                        .HasColumnType("float");

                    b.Property<int?>("RecenzieID")
                        .HasColumnType("int");

                    b.Property<int?>("RezervareID")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("RecenzieID");

                    b.HasIndex("RezervareID");

                    b.ToTable("Restaurant");
                });

            modelBuilder.Entity("Proiect_Medii_Programare.Models.Rezervare", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumarPersoane")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Ora")
                        .HasColumnType("time");

                    b.HasKey("ID");

                    b.ToTable("Rezervare");
                });

            modelBuilder.Entity("Proiect_Medii_Programare.Models.Restaurant", b =>
                {
                    b.HasOne("Proiect_Medii_Programare.Models.Recenzie", null)
                        .WithMany("Restaurante")
                        .HasForeignKey("RecenzieID");

                    b.HasOne("Proiect_Medii_Programare.Models.Rezervare", "Rezervare")
                        .WithMany("Restaurante")
                        .HasForeignKey("RezervareID");

                    b.Navigation("Rezervare");
                });

            modelBuilder.Entity("Proiect_Medii_Programare.Models.Recenzie", b =>
                {
                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("Proiect_Medii_Programare.Models.Rezervare", b =>
                {
                    b.Navigation("Restaurante");
                });
#pragma warning restore 612, 618
        }
    }
}
